name: "Code Quality"

on:
  push:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:

  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Spell Checking"
      uses: streetsidesoftware/cspell-action@v6
      with:
        incremental_files_only: false


  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Format"
      run: cargo fmt --check --verbose


  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Check"
      run: cargo test --verbose
